# Generated by Django 2.1.4 on 2018-12-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'Student_Info',
            },
        ),
    ]
